[project]
name = "comics"
version = "0.1.0"
description = "Tiny webcomic viewer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
]

[tool.uv]
dev-dependencies = []
